/*
 * conf_uart_serial.h
 *
 * Configuration file for UART/USART interfaces in SonarFish
 *
 * Created: 2016-04-02 12:37:32
 *  Author: Max
 */

#ifndef CONF_UART_SERIAL_H
#define CONF_UART_SERIAL_H

/** Debug UART setting */
#define CONF_DEBUG_UART_BAUDRATE	CONF_SFISH_CONSOLE_UART_BAUDRATE
#define CONF_DEBUG_UART_PARITY		UART_MR_PAR_NO
#define CONF_DEBUG_UART				UART0
#define CONF_DEBUG_UART_ID			ID_UART0

/** Sensor UART setting */
#define CONF_SENSOR_UART_BAUDRATE	CONF_SFISH_SENSOR_UART_BAUDRATE
#define CONF_SENSOR_UART_PARITY     UART_MR_PAR_NO
#define CONF_SENSOR_UART			UART1
#define CONF_SENSOR_UART_ID			ID_UART1

/** RS485 UART setting */
#define CONF_RS485_BAUDRATE			CONF_SFISH_RS485_USART_BAUDRATE
#define CONF_RS485_UART_PARITY		UART_MR_PAR_NO
#define CONF_RS485_UART				USART1
#define CONF_RS485_UART_ID			ID_USART1

#endif/* CONF_UART_SERIAL_H_INCLUDED */
