/*
 * conf_sonarcom.h
 *
 * Created: 2015-07-01 00:03:35
 *  Author: Max
 */ 


#ifndef CONF_SONARCOM_H_
#define CONF_SONARCOM_H_

#define SW_VERSION "v0.1"

#define DEBUG_L1

/* Enabled peripheral functions */
#define CONF_SCOM_ENABLE_ANALOG
#define CONF_SCOM_ENABLE_DEBUG_CONSOLE
#define CONF_SCOM_ENABLE_RTCC
#define CONF_SCOM_ENABLE_FREERTOS_GPS_USART
#define CONF_SCOM_ENABLE_FREERTOS_RS485_USART
//#define CONF_SCOM_ENABLE_SPI
#define CONF_SCOM_ENABLE_FREERTOS_SPI
//#define CONF_SCOM_ENABLE_TWI
#define CONF_SCOM_ENABLE_FREERTOS_TWI

/* Enable tasks */
#define CONF_SCOM_ENABLE_GPS_TASK
#define CONF_SCOM_ENABLE_RS485_TASK
#define CONF_SCOM_ENABLE_TIMER_TASK
#define CONF_SCOM_ENABLE_USB_CDC_TASK

/* Debug Console UART */
#define CONF_SCOM_CONSOLE_UART_BAUDRATE		115200

/* Sonar GPS UART */
#define CONF_SCOM_GPS_USART_BAUDRATE		9600

/* Sonar RS485 UART */
//#define CONF_SCOM_RS485_USART_BAUDRATE    921600
#define CONF_SCOM_RS485_USART_BAUDRATE		115200

/* SPI */
#define CONF_SCOM_SPI_BAUDRATE				20000000

#endif /* CONF_SONARCOM_H_ */